### ISSUE TITLE
coder matlab desktop vnc is asking password 

### ISSUE THREAD

**Issue by roshvin** [matifali/coder-templates#18]
coder matlab desktop vnc is asking password 

could you pls suggest how to get / reset.

![image](https://user-images.githubusercontent.com/11057966/215255648-81b64df7-2ac7-4c52-8402-89753b83a56f.png)

**Comment by matifali** [comment]
this is based on official [matlab](https://hub.docker.com/repository/docker/matifali/matlab/general) docker image and default password is: `matlab`

**Comment by roshvin** [comment]
Thanks for your quick help

**Comment by roshvin** [comment]
vnc is getting disconnected in less than a minute , could you pls suggest if  you have noticed this issue.

**Comment by matifali** [comment]
I did not experience any disconnection. We are using it on our local network, an on-premises deployment. 
You may also try to file a bug on @coder or post in their discord for help.

**Comment by matifali** [comment]
> Thanks for your quick help

Sorry for the typo. the official image is here: https://hub.docker.com/r/mathworks/matlab
