### ISSUE TITLE
deeplearning-nvidia unhealthy

### ISSUE THREAD

**Issue by amrhamedp** [matifali/coder-templates#35]
@matifali I tried deeplearning nvidia using latest coder and i get:
Your workspace is running but 1 agent is unhealthy.
I can't see vscode although i selected it

**Comment by matifali** [comment]
@amrhamedp are you able to use other templates?

**Comment by amrhamedp** [comment]
@matifali  yes the default docker template is working well. 
I ran the deeplearning one and docker ps is giving:
c4cf34fa3888   48d7be154cc9                                 "/opt/nvidia/nvidia_…"   3 minutes ago   Up 3 minutes           6006/tcp, 8888/tcp   coder-admin-deep
I can login into it so maybe the agent of vscode is not working for some reason...how can I debug this?

**Comment by amrhamedp** [comment]
@matifali  https://streamable.com/s4dgq7?src=player-page-share

**Comment by matifali** [comment]
@amrhamedp thanks for the screen recording. I am not able to reproduce this. Can you try another template that needs GPU?
![IMG_2542](https://github.com/matifali/coder-templates/assets/10648092/63a5c1c1-79cb-4556-93bf-38bf00b99076)

**Comment by matifali** [comment]
@amrhamedp thanks for the screen recording. I am not able to reproduce this. Can you try another template that needs GPU
![IMG_2542](https://github.com/matifali/coder-templates/assets/10648092/f53c0535-17ea-4808-9e9f-4936692486be)

**Comment by amrhamedp** [comment]
@matifali  I fixed it ...it turned out that dns 1.1.1.1 is not letting my docker update or install anything inside the container (doesn't access internet ) so I removed this line and pushed the terraform again and ran it...now it works.

**Comment by matifali** [comment]
@amrhamedp you can play with the `gpus` option in [`docker_container`](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#gpus) resource.
