### ISSUE TITLE
no nvidia-smi / cuda driver in deeplearning-nvidia

### ISSUE THREAD

**Issue by MathieuMoalic** [matifali/coder-templates#40]
Hi, I can't tell if the template working as intended butit doesn't look like the workspace created with the `deeplearning-nvidia` template have gpu passthrough:
```bash
coder@asdasdasd:~$ ls -la /dev/nvidia*
crw-rw-rw- 1 root root 195, 254 Apr 22 11:11 /dev/nvidia-modeset
crw-rw-rw- 1 root root 235,   0 Apr 22 11:11 /dev/nvidia-uvm
crw-rw-rw- 1 root root 235,   1 Apr 22 11:11 /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 195,   0 Apr 22 11:11 /dev/nvidia0
crw-rw-rw- 1 root root 195, 255 Apr 22 11:11 /dev/nvidiactl
coder@asdasdasd:~$ nvidia-smi
bash: nvidia-smi: command not found
```

I would expect that using `gpus     = "all"` is the same as `podman run --device=nvidia.com/gpu=all ...`. Am I wrong?

**Comment by matifali** [comment]
@MathieuMoalic I have not tested it with Podman and am wondering if the docker provider works with Podman. See these issues for more context:
1. https://github.com/containers/podman/issues/20547
2. https://github.com/kreuzwerker/terraform-provider-docker/issues/113

Also, have you tried with docker?

**Comment by MathieuMoalic** [comment]
You are correct indeed. Terraform doesn't seem to pass the gpu using podman and sadly it doesn't raise an error. Anyways, works perfectly with docker. Thank you!
